### PR TITLE
fix(nodes): fix cluster name too long issue

### PR DESCRIPTION
**Pull request by ysfscream**
https://emqx.atlassian.net/browse/ED-1722

### CODE REVIEW

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-5581)

**Comment by Kinplemelon** [comment]
Can we use https://github.com/emqx/emqx-dashboard5/blob/ysf/1.8.5/src/components/CommonOverflowTooltip.vue to solve this problem?

**Comment by ysfscream** [comment]
@Kinplemelon Yes. I can! I will try replace it.

**Comment by ysfscream** [comment]
@Kinplemelon Updated

**Pull request merged**
