### PR TITLE
feat(pulsar): add `connect_timeout` config parameter

### PR DESCRIPTION
**Pull request by thalesmg**
Related change: https://github.com/emqx/emqx/pull/10757

### CODE REVIEW

**Comment by thalesmg** [comment]
@ysfscream @Kinplemelon is there a process to update `bridge-text-{en,zh}.json`?

**Comment by Kinplemelon** [comment]
> @ysfscream @Kinplemelon is there a process to update `bridge-text-{en,zh}.json`?

Need to manually update `bridge-text-{en,zh}.json`.😅

**Comment by Kinplemelon** [comment]
Thank you for your PR, we will manually add the text for the `connect_timeout` parameter. 
This PR will be merged after https://github.com/emqx/emqx/pull/10757 is merged.

**Review by ysfscream — APPROVED** [review]

**Comment by thalesmg** [comment]
@ysfscream @Kinplemelon Thank you.  https://github.com/emqx/emqx/pull/10757 has been merged today.  :beers:

**Pull request merged**
