### PR TITLE
fix(mongo): remove `topology.pool_size`

### PR DESCRIPTION
**Pull request by thalesmg**
See https://github.com/emqx/emqx/pull/11163

image

### CODE REVIEW

**Comment by Kinplemelon** [comment]
Why is the style on your computer like this? 😱 May I inquire as to which browser you are using?

**Comment by thalesmg** [comment]
> Why is the style on your computer like this? 😱 May I inquire as to which browser you are using?

:joy_cat: 
I'm using Firefox 114.0.2

**Comment by thalesmg** [comment]
Aha, this might be throwing you off (it might have been on when I took the screenshot): https://darkreader.org/help/en/ :dark_sunglasses:

**Comment by Kinplemelon** [comment]
Thank you for your reply! I tried to reproduce it using Firefox + Dark Reader, and it seems to be normal, so I have decided to leave it as it is for now.🤣
image

**Pull request merged**
