### PR TITLE
refactor(connector): adapt new configs in iotdb

### PR DESCRIPTION
**Pull request by Kinplemelon**
https://emqx.atlassian.net/browse/ED-1573

https://emqx.atlassian.net/browse/ED-1583

### CODE REVIEW

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-3732)

**Comment by Kinplemelon** [comment]
@0721Betty FYI. e5.8.1 will add a new schema that can be used to create IoTDB type connector
image

**Comment by 0721Betty** [comment]
> @0721Betty FYI. e5.8.1 will add a new schema that can be used to create IoTDB type connector image

Why does IoTDB need two root refs? Can't it be merged into one root ref like mongoDB/redis?

**Comment by Kinplemelon** [comment]
> > @0721Betty FYI. e5.8.1 will add a new schema that can be used to create IoTDB type connector image
> 
> Why does IoTDB need two root refs? Can't it be merged into one root ref like mongoDB/redis? If they are very different, need to be split into two connectors like kafka?

The developers tried to merge into one schema, then found that there was no way to handle the old data after the merge, so they finally split it into two schemas.

**Review by ysfscream — APPROVED** [review]

**Pull request merged**
